config/routes.rb
Rails.application.routes.draw do


  resources :home, param: :game_room do
    resources :game_players
    resources :rounds
  end


  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game_master.rb
class GameMaster
  attr_accessor :session, :name

  def initialize(session: session, name: name)
    @session = session
    @name = name
  end
end

app/models/game_player.rb
class GamePlayer
  include ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  attr_accessor :session, :player_name, :character_name, :init_bonus, :current_initiative, :id

  def initialize(session: session, player_name: player_name, character_name: character_name, init_bonus: init_bonus)
    @id = SecureRandom.uuid
    @session = session
    @player_name = player_name
    @character_name = character_name
    @init_bonus = init_bonus
    @current_initiative = 0
  end

  def persisted?
    false
  end
end

app/models/room.rb
class Room
  include ActiveModel::Model
  attr_accessor :game_master,
                :number,
                :players,
                :npcs,
                :round,
                :active_player,
                :dynamic_initiative

  def initialize(room: room, session: session, name: name)
    @number = room
    @game_master = GameMaster.new(session: session, name: name)
    @players = []
    @round = 0
    @active_player = ""
    @dynamic_initiative = false

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def get_room(game_room)
    @room = Rails.cache.read(game_room) || Room.new(room: params[:home_game_room], session: session.id, name: "")
    Rails.cache.write game_room, @room
  end
end

app/controllers/game_players_controller.rb
class GamePlayersController < ApplicationController

  def new
    get_room(params[:home_game_room])
    @game_player = GamePlayer.new
    @game_player.session = session.id
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    get_room(params[:home_game_room])

    if is_game_master?
      npc = GamePlayer.new(session: post_params[:session], player_name: post_params[:player_name], character_name: post_params[:character_name], init_bonus: post_params[:init_bonus])
      @room.players.push(npc)
      Rails.cache.write params[:home_game_room], @room
      RoomChannel.broadcast_to("room_#{params[:home_game_room]}", "Update Game Board")

    elsif !is_player?

      player = GamePlayer.new(session: post_params[:session], player_name: post_params[:player_name], character_name: post_params[:character_name], init_bonus: post_params[:init_bonus])
      player.session = session.id
      @room.players.push(player)

      Rails.cache.write params[:home_game_room], @room
      RoomChannel.broadcast_to("room_#{params[:home_game_room]}", "Update Game Board")
    end
  end

  def edit
    get_room(params[:home_game_room])
    idx = @room.players.find_index { |p| p.id == params[:id]}
    @game_player = @room.players[idx]
    respond_to do |format|
      format.js
    end
  end

  def update
    get_room(params[:home_game_room])
    idx = @room.players.find_index { |p| p.id == params[:id]}
    player_to_update = @room.players[idx]
    player_to_update.player_name = update_params[:player_name]
    player_to_update.character_name = update_params[:character_name]
    player_to_update.init_bonus = update_params[:init_bonus]
    @room.players[idx] = player_to_update
    save_changes(@room)
  end



  def is_game_master?
    @room.game_master.session.to_s == session.id.to_s
  end

  def is_player?
    @room.players.any? { |player| player.session.to_s == session.id.to_s}
  end

  def session_exists?
    return is_game_master? ||
        is_player?
  end

  def save_changes(room)

    Rails.cache.write params[:home_game_room], room
    RoomChannel.broadcast_to("room_#{params[:home_game_room]}",
                             title: 'stuff happened!')
  end

  def post_params
    params.require(:game_player).permit(:session, :player_name, :character_name, :init_bonus)
  end

  def update_params
    params.required(:game_player).permit(:player_name, :character_name, :init_bonus)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include CableReady::Broadcaster

  def index
  end

  def show
    get_room(params[:game_room])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def is_game_master?
    @room.game_master.session.to_s == session.id.to_s
  end

  def is_player?
    @room.players.any? { |player| player.session.to_s == session.id.to_s}
  end

  def session_exists?
    return is_game_master? ||
        is_player?
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def create
    get_room(params[:home_game_room])
    @room.round = 1
    @room.dynamic_initiative = update_params[:dynamic_initiative]
    roll_initiative

  end

  def update
    get_room(params[:home_game_room])

    @room.dynamic_initiative = update_params[:dynamic_initiative]
    step_initiative
  end

  def save_changes(room)
    Rails.cache.write params[:home_game_room], room
    RoomChannel.broadcast_to("room_#{params[:home_game_room]}", title: 'Update Gameboard')
  end

  def update_params
    params.require(:room).permit(:dynamic_initiative)
  end

  def step_initiative

    if @room.players.last.id == @room.active_player
      idx = 0
      @room.round += 1

      if @room.dynamic_initiative.to_i > 0
        roll_initiative
      end
    else
      idx = @room.players.index { |player| player.id.to_s == @room.active_player } + 1
    end

    @room.active_player = @room.players[idx].id

    save_changes(@room)
  end

  def roll_initiative
    @room.players.each do |player|
      player.current_initiative = rand(1..20) + player.init_bonus.to_i
    end
    # sorted_players = @room.players.sort { |player| player.current_initiative.to_i }
    sorted_players = @room.players.sort do |a, b|
      if a.current_initiative == b.current_initiative && a.init_bonus.to_i > b.init_bonus.to_i
        -1
      elsif a.current_initiative > b.current_initiative
        -1
      elsif a.current_initiative < b.current_initiative
        1
      else
        0
      end
    end
    @room.players = sorted_players
    @room.active_player = sorted_players.first.nil? ? nil : sorted_players.first.id
    save_changes(@room)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_game_master?(room)
    room.game_master.session.to_s == session.id.to_s
  end

  def is_player?(room)
    room.players.any? { |player| player.session.to_s == session.id.to_s}
  end

  def user_in_game?(room)
    is_player?(room) || is_game_master?(room)
  end
end

app/helpers/game_players_helper.rb
module GamePlayersHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/game_players/_form.html.erb
<h5>Enter Player Details</h5>
<%= form_with model: home_game_player, url: home_game_players_url(home_game_room: params[:home_game_room]), class: "form" do |f| %>
<div class="form-row">
  <%= f.hidden_field :session, value: home_game_player.session %>
  <div class="col-4">
    <%= f.text_field :player_name, class: 'form-control', placeholder: 'Player Name'%>
  </div>
  <div class="col-4">
    <%= f.text_field :character_name, class: 'form-control', placeholder: 'Character Name' %>
  </div>
  <div class="col">
    <%= f.number_field :init_bonus, class: 'form-control', placeholder: 'Initiative Bonus' %>
  </div>
</div>
  <br />
  <%= f.submit "Submit", class: 'btn btn-primary'%>
<% end %>

app/views/game_players/_form_npc.html.erb
<h5>Enter NPC Details</h5>
<%= form_with model: home_game_player, url: home_game_players_url(home_game_room: params[:home_game_room]), class: "form" do |f| %>
<div class="form-row">
  <%= f.hidden_field :session, value: home_game_player.session %>
    <%= f.hidden_field :player_name, value: 'Game Master' %>
  <div class="col-4">
    <%= f.text_field :character_name, class: 'form-control', placeholder: 'Character Name' %>
  </div>
  <div class="col-4">
    <%= f.number_field :init_bonus, class: 'form-control', placeholder: 'Initiative Bonus' %>
  </div>
</div>
  <br />
  <%= f.submit "Add", class: 'btn btn-primary'%>
<% end %>

app/views/game_players/_update_form.html.erb
<%= form_with model: home_game_player, method: "put", url: home_game_player_url(home_game_room: params[:home_game_room], id: home_game_player.id), class: "form" do |f| %>
  <div class="form-row">
    <div class="col-4">
      <%= f.text_field :player_name, class: 'form-control', placeholder: 'Player Name'%>
    </div>
    <div class="col-4">
      <%= f.text_field :character_name, class: 'form-control', placeholder: 'Character Name' %>
    </div>
    <div class="col-4">
      <%= f.number_field :init_bonus, class: 'form-control', placeholder: 'Initiative Bonus' %>
    </div>
  </div>
  <br />
  <%= f.submit "Submit", class: 'btn btn-primary'%>
<% end %>

app/views/game_players/_update_form_npc.html.erb
<%= form_with model: home_game_player, method: "put", url: home_game_player_url(home_game_room: params[:home_game_room], id: home_game_player.id), class: "form" do |f| %>
  <div class="form-row">
    <div class="col-4">
      <%= f.text_field :character_name, class: 'form-control', placeholder: 'Character Name' %>
    </div>
    <div class="col-4">
      <%= f.number_field :init_bonus, class: 'form-control', placeholder: 'Initiative Bonus' %>
    </div>
  </div>
  <br />
  <%= f.submit "Submit", class: 'btn btn-primary'%>
<% end %>

app/views/game_players/edit.js.erb
<% if is_game_master?(@room) %>
document.getElementById('<%= "player_form_#{@game_player.id}" %>').innerHTML = "<%= j render 'update_form_npc', home_game_player: @game_player %>";
<% else %>
document.getElementById('<%= "player_form_#{@game_player.id}" %>').innerHTML = "<%= j render 'update_form', home_game_player: @game_player %>";
<% end %>

app/views/game_players/new.html.erb
Enter your details
<%= render 'form', home_game_player: @game_player %>

app/views/game_players/new.js.erb
<% if is_game_master?(@room) %>
document.getElementById('player_form').innerHTML = "<%= j render 'form_npc', home_game_player: @game_player %>";
<% else %>
document.getElementById('player_form').innerHTML = "<%= j render 'form', home_game_player: @game_player %>";
<% end %>

app/views/home/_game_board.html.erb
<div class="row">

  <div id="turn-order" class="col-xs-12 col-lg-8">

      <div id="join-area">
        <div id="player_form"></div>
        <% if !user_in_game?(room) %>
          <a href="<%= new_home_game_player_url(home_game_room: params[:game_room]) %>" data-remote="true" id="add_player" >Join Game</a>
        <% elsif is_game_master?(room) %>
          <a href="<%= new_home_game_player_url(home_game_room: params[:game_room]) %>" data-remote="true" id="add_player" >Add NPC</a>
        <% end %>
      </div>

    <%= render "turn_order", players: room.players %>
  </div>
  <div id="round-tracker" class="col-xs-12 col-lg-4">
    <%= render "rounds", room: room %>
  </div>
</div>

app/views/home/_rounds.html.erb
<div class="text-center">
<%= "Rounds: #{room.round}" %>
</div>
<% if is_game_master?(room) %>
  <% if room.round <= 0 %>
  <%= render 'rounds/new_form', room: room %>
  <% else %>
  <%= render 'rounds/update_form', locals: {room: room} %>
  <% end %>

<% end %>

app/views/home/_turn_order.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col-10">
    <h3>Turn Order</h3>
<% if players.any? %>
  <% players.each do |player| %>
  <div class="row">
    <div class="card w-100 <%= @room.active_player == player.id ? "border-primary" : "" %>">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <h5 class="card-title"><%= player.character_name %></h5>
            Played by: <%= player.player_name %>
          </div>
          <div class="col">
            <div>Initiative Bonus: <%= player.init_bonus %></div>
            <div>Current Initiative: <%= player.current_initiative %></div>
          </div>
          <div class="col">
            <% if player.session.to_s == session.id.to_s %>
              <%= link_to "Edit", edit_home_game_player_path(params[:game_room], player.id), remote: true, class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
        <div id="<%= "player_form_#{player.id}" %>"></div>
      </div>
    </div>
  </div>
  <% end %>
<% else %>
  <div class="row">
    <div class="card w-100">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <h5 class="card-title text-center">Waiting for players to join</h5>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
  </div>
  <div class="col"></div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col-8 text-center">
    <h3>Initiative Tracker</h3>
    <p>
      Welcome to Initiative Tracker. Click start rolling to create a game room.
      Send the room link to the players so they can join the game.
    </p>
    <p><%= link_to 'Start Rolling', home_path(game_room: SecureRandom.uuid), class: 'btn btn-primary btn-lg btn-block' %></p>
  </div>
  <div class="col-2"></div>
</div>

app/views/home/show.html.erb
<div id="game-room" data-controller="room" data-room-game-room="<%= params[:game_room] %>">

  <div id="game_board">
    <%= render 'game_board', room: @room %>
  </div>

</div>

app/views/home/show.js.erb
document.getElementById('game_board').innerHTML = "<%= j render 'game_board', room: @room %>";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GmTools</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rounds/_new_form.html.erb
<h5>Roll for Initiative</h5>
<%= form_with model: @room, url: "#{params[:game_room]}/rounds", remote: true, class: "form" do |f| %>
  <div class="form">
    <div class="col-sm-12">
      <div class="form-group form-check">
        <%= f.check_box :dynamic_initiative, class: 'form-check-input'%>
        <label class="form-check-label" for="dynamic_initiative">Dynamic Initiative</label>
      </div>
    </div>
    <div class="col-sm-12">
      <%= f.submit "Roll Initiative", class: 'btn btn-primary btn-lg btn-block'%>
    </div>
  </div>
<% end %>

app/views/rounds/_update_form.html.erb
<h5>Roll for Initiative</h5>
<%= form_with model: @room, url: "#{params[:game_room]}/rounds/#{@room.round}", method: :put, remote: true, class: "form" do |f| %>
  <div class="form">
    <div class="col-12">
      <div class="form-group form-check">
        <%= f.check_box :dynamic_initiative, class: 'form-check-input'%>
        <%= f.label :dynamic_initiative %>

      </div>
    </div>
    <div class="col-xs-12">
      <%= f.submit "Next", class: 'btn btn-primary btn-lg btn-block'%>
    </div>
  </div>
<% end %>